# Generated by Django 4.0.3 on 2022-03-30 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(help_text='Menyu nomini kiriting...', max_length=100)),
            ],
            options={
                'verbose_name': 'Menyu ',
                'verbose_name_plural': 'Menyular ',
            },
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(help_text='Mahsulot nomini kiriting...', max_length=200)),
                ('mahsulot_haqida', models.TextField(help_text='Mahsulot haqida ma`lumot')),
                ('rasm', models.ImageField(upload_to='mahsulotlar')),
                ('narx', models.IntegerField(help_text='Mahsulot narxini kiriting')),
                ('menu', models.ForeignKey(help_text='Mahsulot turini tanlang', on_delete=django.db.models.deletion.CASCADE, to='app.menu')),
            ],
            options={
                'verbose_name': 'Mahsulot ',
                'verbose_name_plural': 'Mahsulotlar ',
            },
        ),
    ]
